Controllers/UserManagementController.cs
using klaas.Models;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Identity.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using System.Linq;
using System.Threading.Tasks;

// For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860

namespace ContosoRTM.Controllers
{
    public class UserManagementController : Controller
    {
        private readonly WebshopContext _dbContext;
        private readonly UserManager<Users> _userManager;
        private readonly RoleManager<IdentityRole> _roleManager;

        public UserManagementController(
            WebshopContext dbContext,
            UserManager<Users> userManager,
            RoleManager<IdentityRole> roleManager)
        {
            _dbContext = dbContext;
            _userManager = userManager;
            _roleManager = roleManager;
        }

        [HttpGet]
        public IActionResult Index()
        {

            var vm = new UserManagementIndex
            {
                Users = _dbContext.Users.OrderBy(u => u.Email).ToList()
                // .Include(u => u.Roles).ToList()
            };

            return View(vm);
        }

        [HttpGet]
        public async Task<IActionResult> AddRole(string id)
        {
            var user = await GetUserById(id);
            var vm = new UserManagementAddRole
            {
                Roles = GetAllRoles(),
                UserId = id,
                Email = user.Email
            };
            return View(vm);
        }

        [HttpPost]
        public async Task<IActionResult> AddRole(UserManagementAddRole rvm)
        {
            var user = await GetUserById(rvm.UserId);
            if (ModelState.IsValid)
            {
                var result = await _userManager.AddToRoleAsync(user, rvm.NewRole);
                if (result.Succeeded)
                {
                    return RedirectToAction("Index");
                }
                foreach (var error in result.Errors)
                {
                    ModelState.AddModelError(error.Code, error.Description);
                }
            }
            rvm.Email = user.Email;
            rvm.Roles = GetAllRoles();
            return View(rvm);
            
        }

        private async Task<Users> GetUserById(string id) =>
            await _userManager.FindByIdAsync(id);

        private SelectList GetAllRoles() => new SelectList(_roleManager.Roles.OrderBy(r => r.Name));

    }
}

Views/UserManagement/AddRole.cshtml
@model UserManagementAddRole

<h3>Add Role For @Model.Email</h3>
<div asp-validation-summary="All"></div>
<form asp-controller="UserManagement" asp-action="AddRole">
    <input asp-for="UserId" type="hidden" />
    <select asp-for="NewRole" asp-items="Model.Roles"></select>
    <input type="submit" value="Add Role" />
</form>

Views/UserManagement/Index.cshtml
@using Microsoft.AspNetCore.Identity;
@model UserManagementIndex
@inject UserManager<Users> userManager

<table>
    <thead>
        <tr>
            <th>Email</th>
            <th>Roles</th>
            <th>Options</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var user in Model.Users)
        {
            <tr>
                <td>@user.Email</td>
                <td>@(string.Join(",", await userManager.GetRolesAsync(user)))</td>
                <td><a asp-controller="UserManagement" asp-action="AddRole" asp-route-id="@user.Id">Add Role</a></td>
            </tr>
        }
    </tbody>
</table>