Controllers/ChartController.cs
 using System;
 using System.Collections.Generic;
 using System.Linq;
 using System.Threading.Tasks;
 using klaas.Models;
 using Microsoft.AspNetCore.Mvc;

 using Models;

 namespace klaas.Controllers
 {
     public class ChartController : Controller
     {
         public IActionResult Statistics()
         {
             return View();
         }

         public JsonResult GetTotalSoldData()
         {
             List<object> objs = new List<object>();
             objs.Add(new[] {"x", "Sold Products"});
             objs.Add(new[] { 0, 45 });
             objs.Add(new[] { 1, 87 });
             objs.Add(new[] { 2, 56 });
             objs.Add(new[] { 3, 67 });
             objs.Add(new[] { 4, 58 });
             objs.Add(new[] { 5, 51 });
             objs.Add(new[] { 6, 49 });
             objs.Add(new[] { 7, 67 });
             return Json(objs);
         }

         public JsonResult GetCategorySold()
         {
             List<CategorySoldColsModel> column = new List<CategorySoldColsModel>
             {
                 new CategorySoldColsModel
                 {
                     id = "taxType",
                     label = "Tax Type",
                     type = "string"
                 },
                 new CategorySoldColsModel
                 {
                     id = "percent",
                     label = "Tax Percentage",
                     type = "number"
                 }
             };
             List<CategorySoldRowsModel> row = new List<CategorySoldRowsModel>
             {
                 new CategorySoldRowsModel
                 {
                     c = new List<object>
                     {
                         new CategorySoldColName
                         {
                             v = "Speedboten"
                         },
                         new CategorySoldValName
                         {
                             v = 30
                         }
                     }
                 },
                 new CategorySoldRowsModel
                 {
                     c = new List<object>
                     {
                         new CategorySoldColName
                         {
                             v = "Zeilboten"
                         },
                         new CategorySoldValName
                         {
                             v = 50
                         }
                     }
                 },
                 new CategorySoldRowsModel
                 {
                     c = new List<object>
                     {
                         new CategorySoldColName
                         {
                             v = "Boot Onderdelen"
                         },
                         new CategorySoldValName
                         {
                             v = 20
                         }
                     }
                 }
             };

             CategorySoldModel json = new CategorySoldModel {
                 cols = column,
                 rows = row
             };
             return Json(json);
         }
     }
 }

Controllers/UploadFilesController.cs
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using klaas.Models;
using klaas.products;
using System;

namespace Controllers
{
    public class UploadFilesController : Controller
    {
         private readonly WebshopContext _context;

        public UploadFilesController  (WebshopContext context) {
            _context = context;
        }

        public IActionResult index()
        {
            return View();
        }

        








        #region snippet1
        [HttpPost("UploadFiles")]
        public async Task<IActionResult> index(IFormFile files)
        {
            string content = files.ContentType;

            // full path to file in temp location
            var filePath = Path.GetTempFileName();

            
                if (files.Length > 0)
                {
                    using (var stream = new FileStream(filePath, FileMode.Create))
                    {
                        await files.CopyToAsync(stream);
                    }
                }
            
            // process uploaded files
            // Don't rely on or trust the FileName property without validation.
             string output = "done";
            FileStream fileStream = new FileStream(filePath, FileMode.Open);
                using (StreamReader reader = new StreamReader(fileStream))
                {
                   
                        string line;
                        // Read and display lines from the file until the end of 
                        // the file is reached.
                        while ((line = reader.ReadLine()) != null) 
                        {
                            string[] total = line.Split(';');
                            int id = 0;
                
                            foreach(string i in total){
                                var record = i.Split(new string[] { "," }, StringSplitOptions.None);
                              
                                //productsoortnaam
                                string productss = record[0].ToString();

                                //productsoortidquery
                               var query = from a in _context.Productsoort where a.Naam == productss select a;
                                foreach (var q in query){
                                    id = q.Id;
                                }
                                
                                //productsoortid
                                var productsid = id;

                                
                                var title = record[1].ToString();

                                var price = Convert.ToDouble(record[2]);

                                Productwaarde productwaarde = new Productwaarde{
                                Title = title,
                                Price = price,
                                ProductsoortId = productsid
                            };

                            _context.Productwaarde.Add(productwaarde);
                            _context.SaveChanges();

                             var extrattributen = new List<string>();
                             for (int recor = 3; recor < record.Length; recor++)
                                { 
                                    extrattributen.Add(record[recor]);
                                }
                             var extraatributenarray = extrattributen.ToArray();
                            
                            var productwid = 0;
                            var productwaardequery = from a in _context.Productwaarde where a.Title == title select a;
                                foreach (var q in productwaardequery){
                                    productwid = q.Id;
                                }

                                var attributenid = new List<int>();
                                var queryatrsid = from a in _context.Attribuutsoort where a.ProductsoortId == productsid select a;
                                foreach (var q in queryatrsid){
                                attributenid.Add(q.Id);
                                }
                                
                                //atributenid
                                var atributenidarray = attributenid.ToArray();

                             for (int index = 0; index < atributenidarray.Length; index++){
                              Attribuutwaarde attribuutwaarde = new Attribuutwaarde{
                                  ProductwaardeId = productwid,
                                  AttribuutsoortId = atributenidarray[index],
                                  Waarde = extraatributenarray[index]
                              };
                              _context.Attribuutwaarde.Add(attribuutwaarde);
                            _context.SaveChanges();
                            }
                            }
                            
                            
                        }
                    }
                
            ViewData["Message"] = output;
            return View();
        }
        #endregion
    }
}

Views/UploadFiles/Create4.cshtml
@model IEnumerable<klaas.products.Productwaarde>
@using Microsoft.AspNetCore.Http
@{
    Layout = "";
 }
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">



  <nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="#">Webshop</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="@Url.Action("Mainpage", "Home")">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="@Url.Action("Login", "Account")">Login</a>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Admin
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="@Url.Action("Create", "Products")">Maak product soort aan</a>
          <a class="dropdown-item" href="@Url.Action("Create2", "Products")">Voeg product toe</a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="@Url.Action("Statistics", "Chart")">Site Statistieken</a>
        </div>
      </li>
      <li class="nav-item">
        <a class="nav-link disabled" href="#">Disabled</a>
      </li>
    </ul>
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>
</nav>  
<br>

@{
    //var hi= (ViewData["productsoorten"]);
    var productst = Context.Session.Get<String>("productsoort");
}

@{var i = 1;
}

<div class="row" >
@foreach (var item in Model)
        {
                if ((i%2)!=0){ 
                    
                        <div class="col">
                        <div class="card" style="width: 25rem;">
                            <div class="card-body">
                              <form asp-action="Mainpage">
                                <div id="container" class="form-group">
                                <h5 class="card-title" >@item.Title</h5>
                                <p class="card-text" >$ @item.Price</p>
                                <input type="hidden" name = "hi" value =  '@item.Title' />
                                <input type="submit" class="btn btn-primary" value="Buy"  >
                                </div>
                             </form>             
                            </div>
                        </div>
                    </div>
                
                }
                else{
                    <div class="col">
                        <div class="card" style="width: 25rem;">
                            <div class="card-body">
                               <form asp-action="Mainpage">
                                <div id="container" class="form-group">
                                <h5 class="card-title" >@item.Title</h5>
                                <p class="card-text" >$ @item.Price</p>
                                <input type="hidden" name = "hi" value =  '@item.Title' />
                                <input type="submit" class="btn btn-primary" value="Buy"  >
                                </div>
                             </form> 
                            </div>
                        </div>
                    </div>
                     <div class="w-100"></div>
                    <br>
                }
            i++;
        }
</div>

<script type='text/javascript'>
var names = @Html.Raw(Json.Serialize(ViewData["productsoorten"]));
    //var serializedUsers = JSON.parse(names);
        function addFields(){
		for (i = 0; i <  names.length; i++) { 
            var container = document.getElementById("container1");
            // Clear previous contents of the container
                //container.removeChild(container.lastChild);
                // Append a node with a random text
                var res = names[i].split("= ");
                var end = res[1].split(" }");
                container.appendChild(document.createTextNode(end[0]));
                
				
                // Create an <input> element, set its type and name attributes
                var radio = document.createElement("input");
				radio.type = "radio";
				radio.name = "hi";
				radio.value = end[0];
                container.appendChild(radio);
                // Append a line break 
                container.appendChild(document.createElement("br"));
				}
			}
			window.onload = addFields;
</script>

<div class="row">
    <div class="col-md-4">
        <form asp-action="Create4">
            <div id="container1" class="form-group">
                 Select all<input type="radio" name="hi" value="select all"><br>
            </div>
            <div id="container" class="form-group"></div>
            <div class="form-group">
                <input type="submit" value="Filter" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

Views/UploadFiles/Index.cshtml
<div class="row">
<h2>kaas</h2>
<form method="post" enctype="multipart/form-data">
    <div class="form-group">
        <div class="col-md-10">
            <p>Upload one or more files using this form:</p>
            <input type="file" name="files" multiple />
        </div>
    </div>
    <div class="form-group">
        <div class="col-md-10">
            <input type="submit" value="Upload" />
        </div>
    </div>
</form>
@ViewData["Message"]
</div>